# Generated by Django 4.2.4 on 2024-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softisepapp', '0002_cours_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiciel',
            name='description',
            field=models.TextField(default='lorem ipsum'),
        ),
    ]
