# Generated by Django 5.0.6 on 2024-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softisepapp', '0003_logiciel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logiciel',
            name='cours',
        ),
        migrations.AddField(
            model_name='logiciel',
            name='cours',
            field=models.ManyToManyField(related_name='logiciels', to='softisepapp.cours'),
        ),
    ]
