# Generated by Django 5.0.6 on 2024-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softisepapp', '0004_remove_logiciel_cours_logiciel_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='logiciels',
            field=models.ManyToManyField(related_name='cours_logiciels', to='softisepapp.logiciel'),
        ),
        migrations.AlterField(
            model_name='logiciel',
            name='cours',
            field=models.ManyToManyField(related_name='logiciel_cours', to='softisepapp.cours'),
        ),
    ]
