# Generated by Django 5.0.6 on 2024-05-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softisepapp', '0005_cours_logiciels_alter_logiciel_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logiciel',
            name='cours',
        ),
    ]
