# Generated by Django 5.0.6 on 2024-05-20 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softisepapp', '0007_logiciel_date_de_sortie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='eleves',
            field=models.ManyToManyField(related_name='cours', to=settings.AUTH_USER_MODEL),
        ),
    ]
